pipeline:
  clone:
    image: plugins/git
    depth: 10
    recursive: true
    submodule_update_remote: true
  build-linuix-x64:
    image: cutec/buildhost-lazarus-x64
    commands:
      - lazbuild source/YaSMa.lpr
